/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasimk;

import java.awt.Color;

/**
 *
 * @author User
 */
public class IMKUTS extends javax.swing.JFrame {

    int i=0;
    /**
     * Creates new form NewJFrame
     */
    KonversiSuhu panelKegunaan = new KonversiSuhu();
    Welcome panelWelcome = new Welcome();
    kalkulator panelKalkulator = new kalkulator();
    public IMKUTS() {
        initComponents();
        PanelUtama.add(panelKegunaan);
        PanelUtama.add(panelWelcome);
        PanelUtama.add(panelKalkulator);
        panelWelcome.setVisible(true);
        panelKegunaan.setVisible(false);
        panelKalkulator.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JPanel();
        Welcome = new javax.swing.JButton();
        Kegunaan = new javax.swing.JButton();
        Kalkulator = new javax.swing.JButton();
        LoginName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Tampilan = new javax.swing.JPanel();
        Minimize = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Maximize = new javax.swing.JButton();
        PanelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/369PROF11.png")).getImage());
        setUndecorated(true);

        Menu.setBackground(new java.awt.Color(64, 33, 14));

        Welcome.setBackground(new java.awt.Color(255, 255, 255));
        Welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/371pro.jpg"))); // NOI18N
        Welcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WelcomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WelcomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WelcomeMouseExited(evt);
            }
        });
        Welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeActionPerformed(evt);
            }
        });

        Kegunaan.setBackground(new java.awt.Color(255, 255, 255));
        Kegunaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/371conv.png"))); // NOI18N
        Kegunaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KegunaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KegunaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KegunaanMouseExited(evt);
            }
        });
        Kegunaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KegunaanActionPerformed(evt);
            }
        });

        Kalkulator.setBackground(new java.awt.Color(255, 255, 255));
        Kalkulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/371cal.png"))); // NOI18N
        Kalkulator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KalkulatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KalkulatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KalkulatorMouseExited(evt);
            }
        });
        Kalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KalkulatorActionPerformed(evt);
            }
        });

        LoginName.setBackground(new java.awt.Color(255, 255, 255));
        LoginName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LoginName.setForeground(new java.awt.Color(255, 255, 255));
        LoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/371wel1.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Kalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kegunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Kegunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Kalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        Tampilan.setBackground(new java.awt.Color(78, 41, 16));

        Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Minimize.setText("_");
        Minimize.setSelected(true);
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setText("X");
        Exit.setSelected(true);
        Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ExitMouseMoved(evt);
            }
        });
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Maximize.setBackground(new java.awt.Color(255, 255, 255));
        Maximize.setText("<>");
        Maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Maximize.setSelected(true);
        Maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaximizeMouseExited(evt);
            }
        });
        Maximize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximizeActionPerformed(evt);
            }
        });

        PanelUtama.setLayout(new javax.swing.BoxLayout(PanelUtama, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout TampilanLayout = new javax.swing.GroupLayout(Tampilan);
        Tampilan.setLayout(TampilanLayout);
        TampilanLayout.setHorizontalGroup(
            TampilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Maximize, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addContainerGap())
            .addGroup(TampilanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        TampilanLayout.setVerticalGroup(
            TampilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilanLayout.createSequentialGroup()
                .addGroup(TampilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(Minimize)
                    .addComponent(Maximize))
                .addGap(89, 89, 89)
                .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tampilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Tampilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(758, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        setState(WIDTH);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void MaximizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximizeActionPerformed
        if (getExtendedState()==NORMAL) {           
           setExtendedState(IMKUTS.MAXIMIZED_BOTH);
        }else{
           setExtendedState(IMKUTS.NORMAL);            
        }        
    }//GEN-LAST:event_MaximizeActionPerformed

    private void ExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseMoved
       
    }//GEN-LAST:event_ExitMouseMoved

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setBackground(Color.RED);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setBackground(Color.WHITE);
    }//GEN-LAST:event_ExitMouseExited

    private void MaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeMouseEntered
        Maximize.setBackground(Color.RED);
    }//GEN-LAST:event_MaximizeMouseEntered

    private void MaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeMouseExited
        Maximize.setBackground(Color.WHITE);
    }//GEN-LAST:event_MaximizeMouseExited

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        Minimize.setBackground(Color.RED);
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        Minimize.setBackground(Color.WHITE);
    }//GEN-LAST:event_MinimizeMouseExited

    private void KegunaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KegunaanMouseEntered
        Kegunaan.setBackground(Color.RED);
        Kegunaan.setForeground(Color.GREEN);
    }//GEN-LAST:event_KegunaanMouseEntered

    private void KegunaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KegunaanActionPerformed
         
    }//GEN-LAST:event_KegunaanActionPerformed

    private void KegunaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KegunaanMouseExited
        // TODO add your handling code here:
        Kegunaan.setBackground(Color.WHITE);
        Kegunaan.setForeground(Color.BLACK);
    }//GEN-LAST:event_KegunaanMouseExited

    private void KalkulatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KalkulatorMouseEntered
        // TODO add your handling code here:
        Kalkulator.setBackground(Color.RED);
        Kalkulator.setForeground(Color.GREEN);
    }//GEN-LAST:event_KalkulatorMouseEntered

    private void KalkulatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KalkulatorMouseExited
        // TODO add your handling code here:
        Kalkulator.setBackground(Color.WHITE);
        Kalkulator.setForeground(Color.BLACK);
    }//GEN-LAST:event_KalkulatorMouseExited

    private void KegunaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KegunaanMouseClicked

        panelKegunaan.setVisible(true);
        panelWelcome.setVisible(false);
        panelKalkulator.setVisible(false);
    }//GEN-LAST:event_KegunaanMouseClicked

    private void WelcomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMouseEntered
        // TODO add your handling code here:
        Welcome.setBackground(Color.RED);
    }//GEN-LAST:event_WelcomeMouseEntered

    private void WelcomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMouseExited
        // TODO add your handling code here:
        Welcome.setBackground(Color.WHITE);
    }//GEN-LAST:event_WelcomeMouseExited

    private void WelcomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMouseClicked
        // TODO add your handling code here:
        panelKegunaan.setVisible(false);
        panelWelcome.setVisible(true);
        panelKalkulator.setVisible(false);
    }//GEN-LAST:event_WelcomeMouseClicked

    private void KalkulatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KalkulatorMouseClicked
        panelKegunaan.setVisible(false);
        panelWelcome.setVisible(false);
        panelKalkulator.setVisible(true);
    }//GEN-LAST:event_KalkulatorMouseClicked

    private void KalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KalkulatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KalkulatorActionPerformed

    private void WelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WelcomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMKUTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMKUTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMKUTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMKUTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KonversiSuhu panelKegunaan = new KonversiSuhu();
                new IMKUTS().setVisible(true);
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Kalkulator;
    private javax.swing.JButton Kegunaan;
    protected javax.swing.JLabel LoginName;
    private javax.swing.JButton Maximize;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Minimize;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel Tampilan;
    private javax.swing.JButton Welcome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
