/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasimk;

import javax.swing.ButtonGroup;

/**
 *
 * @author hanif
 */
public class KonversiSuhu extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    ButtonGroup bg1 = new ButtonGroup();
    
    public Double input;
    public Double celcius;
    public Double fahrenheit;
    public Double reamur;
    public Double kelvin;
    public String hasilcelcius;
    public String hasilfahrenheit;
    public String hasilreamur;
    public String hasilkelvin;
    public KonversiSuhu() {
        initComponents();
        groupButton();
        txtCelcius.setEditable(false);
        txtFahrenheit.setEditable(false);
        txtReamur.setEditable(false);
        txtKelvin.setEditable(false);
    }
    
private void celcius(){
    input=Double.parseDouble(txtAwal.getText());
    
    celcius=input;
    fahrenheit=celcius*1.8+32;
    reamur=celcius*0.8;
    kelvin=celcius+273;
    
    hasilcelcius=Double.toString(celcius);
    txtCelcius.setText(hasilcelcius);
    
    hasilfahrenheit=Double.toString(fahrenheit);
    txtFahrenheit.setText(hasilfahrenheit);
    
    hasilreamur=Double.toString(reamur);
    txtReamur.setText(hasilreamur);
    
    hasilkelvin=Double.toString(kelvin);
    txtKelvin.setText(hasilkelvin);
}

private void fahrenheit(){
    input=Double.parseDouble(txtAwal.getText());
    
    fahrenheit=input;
    celcius=(fahrenheit-32)/1.8;
    reamur=(fahrenheit-32)*(4/9);
    kelvin=((fahrenheit-32)*(5/9))+273;
    
    hasilcelcius=Double.toString(celcius);
    txtCelcius.setText(hasilcelcius);
    
    hasilfahrenheit=Double.toString(fahrenheit);
    txtFahrenheit.setText(hasilfahrenheit);
    
    hasilreamur=Double.toString(reamur);
    txtReamur.setText(hasilreamur);
    
    hasilkelvin=Double.toString(kelvin);
    txtKelvin.setText(hasilkelvin);
    
}

public void reamur(){
    input=Double.parseDouble(txtAwal.getText());
    
    reamur=input;
    celcius=reamur*5/4;
    fahrenheit=(reamur*9/4)+32;
    kelvin=(reamur*5/4)+273;
    
    hasilcelcius=Double.toString(celcius);
    txtCelcius.setText(hasilcelcius);
    
    hasilfahrenheit=Double.toString(fahrenheit);
    txtFahrenheit.setText(hasilfahrenheit);
    
    hasilreamur=Double.toString(reamur);
    txtReamur.setText(hasilreamur);
    
    hasilkelvin=Double.toString(kelvin);
    txtKelvin.setText(hasilkelvin);
}

private void kelvin(){
    input=Double.parseDouble(txtAwal.getText());
    
    kelvin=input;
    celcius=kelvin-273;
    fahrenheit=((kelvin-273)+32)*9/5;
    reamur=(kelvin-273)*4/5;
    
    hasilcelcius=Double.toString(celcius);
    txtCelcius.setText(hasilcelcius);
    
    hasilfahrenheit=Double.toString(fahrenheit);
    txtFahrenheit.setText(hasilfahrenheit);
    
    hasilreamur=Double.toString(reamur);
    txtReamur.setText(hasilreamur);
    
    hasilkelvin=Double.toString(kelvin);
    txtKelvin.setText(hasilkelvin);
}

private void groupButton(){
    
    
    bg1.add(rbCelcius);
    bg1.add(rbFahrenheit);
    bg1.add(rbReamur);
    bg1.add(rbKelvin);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtAwal = new javax.swing.JTextField();
        rbCelcius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbReamur = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCelcius = new javax.swing.JTextField();
        txtFahrenheit = new javax.swing.JTextField();
        txtReamur = new javax.swing.JTextField();
        txtKelvin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(444, 372));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Suhu Awal");
        add(jLabel1);
        jLabel1.setBounds(10, 14, 90, 15);

        txtAwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAwalKeyTyped(evt);
            }
        });
        add(txtAwal);
        txtAwal.setBounds(84, 11, 350, 30);

        rbCelcius.setForeground(new java.awt.Color(255, 255, 255));
        rbCelcius.setText("Celcius");
        rbCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelciusActionPerformed(evt);
            }
        });
        add(rbCelcius);
        rbCelcius.setBounds(70, 50, 70, 23);

        rbFahrenheit.setForeground(new java.awt.Color(255, 255, 255));
        rbFahrenheit.setText("Farenheit");
        add(rbFahrenheit);
        rbFahrenheit.setBounds(160, 50, 90, 23);

        rbReamur.setForeground(new java.awt.Color(255, 255, 255));
        rbReamur.setText("Reamur");
        add(rbReamur);
        rbReamur.setBounds(260, 50, 80, 23);

        rbKelvin.setForeground(new java.awt.Color(255, 255, 255));
        rbKelvin.setText("Kelvin");
        add(rbKelvin);
        rbKelvin.setBounds(350, 50, 70, 23);

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        add(btnKonversi);
        btnKonversi.setBounds(63, 80, 80, 23);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear);
        btnClear.setBounds(157, 80, 70, 23);

        btnBatal.setText("Batal");
        add(btnBatal);
        btnBatal.setBounds(250, 80, 70, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hasil Konversi");
        add(jLabel2);
        jLabel2.setBounds(80, 110, 100, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Celcius");
        add(jLabel3);
        jLabel3.setBounds(20, 150, 70, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Farenheit");
        add(jLabel4);
        jLabel4.setBounds(20, 180, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reamur");
        add(jLabel5);
        jLabel5.setBounds(20, 210, 70, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kelvin");
        add(jLabel6);
        jLabel6.setBounds(20, 240, 60, 15);

        txtCelcius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelciusKeyTyped(evt);
            }
        });
        add(txtCelcius);
        txtCelcius.setBounds(86, 143, 348, 30);
        add(txtFahrenheit);
        txtFahrenheit.setBounds(86, 174, 348, 30);
        add(txtReamur);
        txtReamur.setBounds(86, 205, 348, 30);
        add(txtKelvin);
        txtKelvin.setBounds(86, 236, 348, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3692.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMinimumSize(new java.awt.Dimension(444, 373));
        jLabel7.setPreferredSize(new java.awt.Dimension(444, 373));
        add(jLabel7);
        jLabel7.setBounds(0, -10, 450, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        if (rbCelcius.isSelected()) {
            celcius();
        }else if (rbFahrenheit.isSelected()) {
            fahrenheit();
        }else if (rbReamur.isSelected()) {
            reamur();
        }else if (rbKelvin.isSelected()) {
            kelvin();
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAwal.setText("");
        txtCelcius.setText("");
        txtFahrenheit.setText("");
        txtReamur.setText("");
        txtKelvin.setText("");
        bg1.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void rbCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCelciusActionPerformed

    private void txtAwalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAwalKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAwalKeyTyped

    private void txtCelciusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelciusKeyTyped
       
    }//GEN-LAST:event_txtCelciusKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbReamur;
    private javax.swing.JTextField txtAwal;
    private javax.swing.JTextField txtCelcius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    private javax.swing.JTextField txtReamur;
    // End of variables declaration//GEN-END:variables
}
