/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasimk;

import java.awt.Toolkit;

/**
 *
 * @author hanif
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    IMKUTS imkuts = new IMKUTS();
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
       
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Masuk = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/369PROF11.png")).getImage());
        setPreferredSize(new java.awt.Dimension(444, 373));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        Masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasukMouseClicked(evt);
            }
        });
        getContentPane().add(Masuk);
        Masuk.setBounds(170, 270, 90, 40);

        InputNama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaActionPerformed(evt);
            }
        });
        InputNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputNamaKeyReleased(evt);
            }
        });
        getContentPane().add(InputNama);
        InputNama.setBounds(90, 190, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/371cx.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 330, 250);

        Background.setBackground(new java.awt.Color(153, 0, 51));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3692.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 440, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaActionPerformed
       
    }//GEN-LAST:event_InputNamaActionPerformed

    private void InputNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNamaKeyReleased
         if (!(InputNama.getText().equals(""))) {
            Masuk.setEnabled(true);
            
        }
    }//GEN-LAST:event_InputNamaKeyReleased

    private void MasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasukMouseClicked
        // TODO add your handling code here:
        imkuts.LoginName.setText(InputNama.getText());
        imkuts.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_MasukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField InputNama;
    private javax.swing.JLabel Masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
}
